### ISSUE TITLE
Добавить мейнтейнера в npm

### ISSUE THREAD

**Issue by in19farkt** [fullstack-development/redux-make-communication#11]
Нужно добавить меня в мейнтейнеры пакета, чтобы я смог публиковать от себя новые версии и настроить CI.

1. Нужно локально залогиниться в учетку sergey@fullstack-development.com
  - Проверка на залогиненность `npm whoami`
  - Залогиниться `npm login`, далее вводим емайл и пароль
2. Команда для добавления мейнтейнера `npm owner in_farkt redux-make-communication`

**Comment by Znack** [comment]
Судя по всему такой никнейм не определяется нпм-ом :(

**Comment by Znack** [comment]
Добавил
