### ISSUE TITLE
Экспорт типов

### ISSUE THREAD

**Issue by chmnkh** [fullstack-development/redux-make-communication#7]
раз уж мы вынесли это в отдельный пакет, то почему у нас все еще типы для коммьюникейшена объявлены в проекте, а не импортятся из этого пакета?

надо тут в индекс.тс экспорт типов добавить по идее

**Comment by in19farkt** [comment]
не понятно о чем ты тут говоришь))

**Comment by in19farkt** [comment]
а не, понятно, не понял сразу в каком репозитории нахожусь)))

**Comment by clicktronix** [comment]
типы лежат в нпм пакете, оттуда можно их дергать по идее

**Comment by chmnkh** [comment]
их можно импортнуть, если вглубь либы залезть)
но такого не должно быть, должна быть возможность просто из индекса импортнуть, то есть так:
```import { ICommunication } from 'lib'```
а не так:
```import { ICommunication } from `lib/.../namespace```

**Comment by clicktronix** [comment]
Странно, они кладутся в npm в index.d.ts, там нет неймспейса, или я чет путаю
